### ISSUE TITLE
Practica 8 - Diagrama de clases - DiegoAlexisCarlosCruz

### ISSUE THREAD

**Issue by Diego047** [SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-equipo-de-irving#3]
[Practica8 Diagrama de clases (1).pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-diagrama-de-clases-equipo-de-irving/files/10222190/Practica8.Diagrama.de.clases.1.pdf)

**Comment by ang3-l32** [comment]
48

**Comment by josealfredo79** [comment]
Faltan los parametros en los métodos
![image](https://user-images.githubusercontent.com/58342642/207184550-412cd41b-25e9-4154-abcf-12e2585ace84.png)

**Comment by ang3-l32** [comment]
YA SE REALIZO LAS CORRECIONES A LA ACTIVIDAD 8 DE DIAGRAMAS DE CLASES

**Comment by josealfredo79** [comment]
Revisado...
